### PR TITLE
Various improvements

### PR DESCRIPTION
**Pull request by driv3r**
- [x] Added `reraise` statement in `trace` decorator method, otherwise it swallows errors
- [x] Modified a bit ecto trace to always return back `log_entry`, otherwise other loggers fail
- [x] Updated `Confex` to v3.2 which allows you to set custom adapters

Besides that I found other things that I wanted to clarify first:
- documentation needs to be updated, as there's no `traced` decorator, nor `trace` method which accepts `Keyword` of arguments, which leads us to next issue
- at the moment traces are sent as `unknown` always, so it doesn't take under consideration settings defined in config, this should be probably fixed by applying Keyword args in `trace` method? 
- plugs could accept `x-ddtrace-parent_trace_id` and `x-ddtrace-parent_span_id` headers in order to support distributed tracing, and we could add some method to return this list of headers based on current span so You could just pass them further with api call, wdys?

### CODE REVIEW

**Comment by zachdaniel** [comment]
Awesome work, I will look at it in just a few minutes :)

**Comment by zachdaniel** [comment]
* Headers for distributed tracing are a definite yes.
* We should add a traced/1 decorator that allows passing the keyword list.
* We should default values to what is in the config when they are not set. Right now, I believe it is the `AddContext` plug that uses the configs, so if that isn't being used then those configs don't do anything.

**Comment by zachdaniel** [comment]
I'm creating issues for those three things.

**Comment by zachdaniel** [comment]
@driv3r if there are no other changes you'd like to make to this PR, we can get it merged. Once the other issues I made from this have been resolved, we'll package up a release.

**Comment by driv3r** [comment]
:+1:  I can probably start working on those right away ;)

**Pull request merged**
