### PR TITLE
make the ecto service name configurable

### PR DESCRIPTION
**Pull request by craig-day**
First thanks for this amazing tool! 

This adds a simple configuration to the ecto logger to allow for customizing the service name. This can be useful if you have a lot of projects using ecto and you want to ensure the traces stay separate. This is also [supported by the Datadog official APM clients](http://www.rubydoc.info/github/DataDog/dd-trace-rb/#Configure_the_tracer_with_initializers) so this brings the Elixir client closer to them.

I noticed there is currently no mention of the ecto logger tracer in the readme, so I didn't mention this configuration there. 

Hope others find this helpful!

/cc @zachdaniel

### CODE REVIEW

**Comment by zachdaniel** [comment]
This is great :). What would you think about making the service name default to the name of the repo module?  Since if you have many repos, they'll all have different names.  I *think* that you can get the repo module off of a log entry.

**Comment by craig-day** [comment]
@zachdaniel unfortunately it doesn't look like we get the repo in the log entry.  The `source` field contains the schema (table) name.

**Comment by zachdaniel** [comment]
I'll merge this today and build a point release.

**Comment by craig-day** [comment]
@zachdaniel that's great. Looking forward to it!

**Pull request merged**
